/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#3E5F36',
        'on-primary': '#ffffff',
        'primary-container': '#C3E8B8',
        'on-primary-container': '#092007',
        'primary-fixed': '#C3E8B8',
        'on-primary-fixed': '#031503',
        'primary-fixed-dim': '#A8CC9E',
        secondary: '#A65D43',
        'on-secondary': '#ffffff',
        'secondary-container': '#FCDDD4',
        'on-secondary-container': '#3B120A',
        tertiary: '#D4A373',
        'on-tertiary': '#3D2400',
        'tertiary-container': '#F5E3CA',
        'on-tertiary-container': '#3D2400',
        'tertiary-fixed': '#F5E3CA',
        'on-tertiary-fixed': '#3D2400',
        background: '#F5F4EF',
        'on-background': '#1A1C18',
        surface: '#F5F4EF',
        'on-surface': '#1A1C18',
        'surface-variant': '#DDDDD5',
        'on-surface-variant': '#444841',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F0EDE8',
        'surface-container': '#EAEAE2',
        'surface-container-high': '#E4E3DB',
        'surface-container-highest': '#DEDDD5',
        'surface-dim': '#D6D4CE',
        'inverse-surface': '#2F312D',
        'inverse-on-surface': '#F1F0EA',
        outline: '#76736A',
        'outline-variant': '#C5C4BC',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Newsreader', 'serif'],
        label: ['Manrope', 'sans-serif'],
        newsreader: ['Newsreader', 'serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
