/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#4A5D45',
        'on-primary': '#ffffff',
        'primary-container': '#CCD7C8',
        'on-primary-container': '#0C1F0E',
        'primary-fixed': '#CCD7C8',
        'on-primary-fixed': '#091407',
        'primary-fixed-dim': '#b0ccaa',
        secondary: '#5D5F5A',
        'on-secondary': '#ffffff',
        'secondary-container': '#E2E4DE',
        'on-secondary-container': '#1A1C18',
        tertiary: '#7A5733',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#FFDDBB',
        'on-tertiary-container': '#2B1700',
        'tertiary-fixed': '#FFDDBB',
        'on-tertiary-fixed': '#2B1700',
        background: '#FCF9F5',
        'on-background': '#1A1C18',
        surface: '#FCF9F5',
        'on-surface': '#1A1C18',
        'surface-variant': '#E1E4DC',
        'on-surface-variant': '#444841',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F7F4F0',
        'surface-container': '#F1EFEA',
        'surface-container-high': '#EBE9E4',
        'surface-container-highest': '#E6E3DE',
        'surface-dim': '#D9DBD4',
        'inverse-surface': '#2F312D',
        'inverse-on-surface': '#F1F1EB',
        outline: '#757971',
        'outline-variant': '#C4C8BF',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Newsreader', 'serif'],
        label: ['Manrope', 'sans-serif'],
        newsreader: ['Newsreader', 'serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
